version: '3.3'
services:
  #Serveur de base de données
  fleks_db:
    container_name: 'cFleks_db'
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pTJ3D7GzXpGBLq98'
      POSTGRES_DB: fleks
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data/
    networks:
      - fleks_network

  #Serveur web pour gérer les requetes vers le back-office
  fleks_back_web:
    container_name: 'cFleks_back_web'
    image: nginx
    restart: always
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - /home/admindev/ssl_entry_point/dhparam:/etc/nginx/dhparam
      - /home/admindev/ssl_entry_point/certbot/conf/:/etc/nginx/ssl/
      - /home/admindev/ssl_entry_point/certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - fleks_db
    ports:
      - '8080:443'
  #Serveur d'application du back-office
  fleks_back_app:
    depends_on:
      - fleks_back_web
    container_name: 'cFleks_back'
    image: 'consultech225/portal_backend:${TAG}'
    volumes:
      - ./application/files:/.jmix/work/filestorage
      - ./application/config/application.properties:/home/app/config/application.properties
      - ./application/config/application-test.properties:/home/app/config/application-test.properties
      - ./application/logs:/.jmix/work/log
    ports:
      - '8082:8080'
    networks:
      - fleks_network
volumes:
  app-config:

networks:
  fleks_network:
